name: worddle

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0
        with:
          flutter-version: '2.10.0'

      - name: Install Dependencies
        run: flutter packages get -v

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Build Android
        run: flutter build apk --release -v --flavor production --target lib/main_production.dart -v --split-per-abi

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"
          token: ${{ secrets.ACCESS_TOKEN }}
        
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
